- import_playbook: centos_docker_install.yml

- hosts: localhost
  gather_facts: no

  tasks:

  - name: executing setenforce 0
    raw: setenforce 0

  - name: set the selinux to permissive
    selinux:
     policy: targeted
     state: permissive

  - name: adding the kubernetes repo
    yum_repository:
     name: kubernetes
     description: official repo for kubernetes
     baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
     gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
     gpgcheck: yes

  - name: installing kubernetes
    yum:
     name: "{{ item }}"
     state: latest
     update_cache: yes
    with_items:
    - kubelet
    - kubeadm
    - kubectl

  - name: enabling and starting kubelet
    systemd:
     name: kubelet
     enabled: yes
     state: started

  - name: updating iptables
    copy:
     src: k8s.conf
     dest: /etc/sysctl.d/k8s.conf

  - name: enable changes to iptables
    raw: sysctl --system
