- import_playbook: centos_docker_install.yml
- hosts: localhost
  gather_facts: no
  tasks:
  - name: adding kube repo
    copy:
     src: kubernetes.repo
     dest: /etc/yum.repos.d/kubernetes.repo

  - name: disabling SELinux
    raw: setenforce 0

  - name: making SELinux changes permanent
    selinux:
     policy: targeted
     state: permissive

  - name: installing kubernetes
    yum:
     name: "{{ item }}"
     state: present
    with_items:
    - kubelet
    - kubeadm
    - kubectl

  - name: correcting iptables config
    copy:
     src: k8s.conf
     dest: /etc/sysctl.d/k8s.conf

  - name: loading sysctl config
    raw: sysctl --system
