- hosts: localhost
  gather_facts: no
  tasks:
  - name: installing docker
    yum:
     name: docker
     state: present
     update_cache: yes

  - name: enabling docker to start up on boot
    systemd:
     name: docker
     enabled: yes
     state: started
