- hosts: localhost
  gather_facts: yes
  tasks:
  - name: Remove any old docker repos
    apt:
     name: "{{ item }}"
     state: absent
    with_items:
    - docker 
    - docker-engine 
    - docker.io

  - name: Install packages to allow apt to use a repository over HTTPS
    apt:
     name: "{{ item }}"
     state: present
     update_cache: yes
    with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common

  - name: Add Docker’s official GPG key
    apt_key:
     url: https://download.docker.com/linux/ubuntu/gpg
     state: present

  - name: add the docker repo
    apt_repository:
     repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
     state: present
     filename: docker-ce

  - name: installing docker
    apt:
     name: docker-ce
     update_cache: yes
     state: present
